---
- name: install-docker-dependencies
  apt: update_cache=yes name={{item}} state=present
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

- name: add-docker-apt-signing-key
  apt_key: url={{item}} state=present
  with_items:
  - https://download.docker.com/linux/ubuntu/gpg

- name: add-docker-apt-repository
  apt_repository: repo={{item}} state=present
  with_items:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: install-docker-ce
  apt: update_cache=yes name={{item}} state=present
  with_items:
  - docker-ce
  - docker-ce-cli
  - containerd.io

